name: syncfusion_flutter_datepicker
description: The Flutter Date Range Picker widget allows users to easily select dates or a range of dates. It has four built-in views that allow quick navigation to the desired date.
version: 21.1.35
homepage: https://github.com/syncfusion/flutter-examples

environment:
  sdk: ">=2.17.0 <=3.1.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ">=0.17.0 <0.20.0"
  syncfusion_flutter_core: ^22.2.9

dev_dependencies:
  flutter_test:
    sdk: flutter
